/**
 * content-schema.js — Schema-Definitionen aller Collections
 * 
 * Dient als Doku für Agents: welche Collections gibt's, welche Felder,
 * welche Typen. Jeder Eintrag liegt in src/data/{collection}/{slug}/index.json
 * 
 * Singletons liegen direkt in src/data/{name}.json
 */

export const COLLECTIONS = {
  regionen: {
    label: 'Regionen',
    slugLabel: 'titel',
    fields: {
      titel:          { type: 'string', required: true, desc: 'Name der Region' },
      emoji:          { type: 'string', desc: 'Emoji-Icon (z.B. 🏔️)' },
      farbe:          { type: 'string', desc: 'Akzentfarbe als Hex (z.B. #0051BA)' },
      kurzbeschreibung:{ type: 'text', desc: 'Kurzer Teaser (1 Satz)' },
      beschreibung:   { type: 'richtext', desc: 'HTML-Inhalt mit Highlights' },
      bewertung:      { type: 'number', min: 1, max: 5 },
      hoehe:          { type: 'string', desc: 'z.B. "3.774 m"' },
      flaeche:        { type: 'string', desc: 'z.B. "530 km²"' },
      einwohner:      { type: 'string' },
      tags:           { type: 'array', items: 'string' },
      featured:       { type: 'boolean' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/regionen/innsbruck/hero.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/regionen/innsbruck/hero.webp)' },
    },
    related: ['unterkuenfte', 'orte', 'gastro'],
  },

  unterkuenfte: {
    label: 'Unterkünfte',
    slugLabel: 'name',
    fields: {
      name:          { type: 'string', required: true },
      typ:           { type: 'enum', values: ['hotel', 'ferienwohnung', 'bauernhof', 'jugendherberge', 'camping'] },
      sterne:        { type: 'number', min: 1, max: 5 },
      tier:          { type: 'enum', values: ['gold', 'silver', 'basic'], desc: 'Free-Mium Tier' },
      preis_ab:      { type: 'number', desc: 'Preis in €/Nacht' },
      ort:           { type: 'string' },
      plz:           { type: 'string' },
      region:        { type: 'string', desc: 'Slug der Region (z.B. "oetztal")' },
      adresse:       { type: 'string' },
      telefon:       { type: 'string' },
      email:         { type: 'string' },
      webseite:      { type: 'url' },
      beschreibung:  { type: 'richtext' },
      ausstattung:   { type: 'array', items: 'string', desc: 'z.B. wifi, fruehstueck, sauna' },
      tags:          { type: 'array', items: 'string' },
      status:        { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:        { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/unterkuenfte/hotel-xyz/zimmer.webp)' },
      hero_bild:     { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/unterkuenfte/hotel-xyz/hero.webp)' },
    },
    related: [],
  },

  camping: {
    label: 'Campingplätze',
    slugLabel: 'name',
    fields: {
      name:          { type: 'string', required: true },
      typ:           { type: 'string', desc: 'Stellplatz-Typ (z.B. camping)' },
      stellplatz_typ:{ type: 'string', desc: 'Z.B. Reisemobil, Wohnwagen, Zelt, Parzelle' },
      saison:        { type: 'string', desc: 'Öffnungszeiten / Saison (z.B. Mai-Oktober)' },
      preis_ab:      { type: 'number', desc: 'Preis pro Nacht in €' },
      ort:           { type: 'string' },
      plz:           { type: 'string' },
      region:        { type: 'string', desc: 'Slug der Region (z.B. "oetztal")' },
      adresse:       { type: 'string' },
      telefon:       { type: 'string' },
      email:         { type: 'string' },
      webseite:      { type: 'url' },
      beschreibung:  { type: 'richtext' },
      ausstattung:   { type: 'array', items: 'string', desc: 'Z.B. stromanschluss, wasseranschluss, sanitäranlagen, entsorgung' },
      tags:          { type: 'array', items: 'string' },
      tier:          { type: 'enum', values: ['gold', 'silver', 'basic'], desc: 'Free-Mium Tier' },
      koordinaten:   { type: 'object', desc: '{ lat, lng }' },
      status:        { type: 'enum', values: ['published', 'draft', 'archived'] },
    },
    related: [],
  },

  gastro: {
    label: 'Gastronomie',
    slugLabel: 'name',
    fields: {
      name:           { type: 'string', required: true },
      emoji:          { type: 'string' },
      farbe:          { type: 'string' },
      kategorie:      { type: 'string', desc: 'z.B. cafe, restaurant, bar' },
      kurzbeschreibung:{ type: 'text' },
      beschreibung:   { type: 'richtext' },
      ort:            { type: 'string' },
      adresse:        { type: 'string' },
      region:         { type: 'string' },
      telefon:        { type: 'string' },
      email:          { type: 'string' },
      webseite:       { type: 'url' },
      preis:          { type: 'string', desc: 'Preiskategorie (€, €€, €€€)' },
      tags:           { type: 'array', items: 'string' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/gastro/cafe-central/innen.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/gastro/cafe-central/hero.webp)' },
    },
    related: [],
  },

  orte: {
    label: 'Orte',
    slugLabel: 'name',
    fields: {
      name:           { type: 'string', required: true },
      emoji:          { type: 'string' },
      farbe:          { type: 'string' },
      kurzbeschreibung:{ type: 'text' },
      hoehe:          { type: 'string' },
      einwohner:      { type: 'string' },
      region:         { type: 'string' },
      tags:           { type: 'array', items: 'string' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/orte/innsbruck/altstadt.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/orte/innsbruck/hero.webp)' },
    },
    related: ['unterkuenfte', 'gastro'],
  },

  sehenswuerdigkeiten: {
    label: 'Sehenswürdigkeiten',
    slugLabel: 'name',
    fields: {
      name:           { type: 'string', required: true },
      emoji:          { type: 'string' },
      farbe:          { type: 'string' },
      kategorie:      { type: 'enum', values: ['natur', 'kultur', 'aussicht', 'sport', 'museum', 'kirche', 'burg', 'wanderung'] },
      kurzbeschreibung:{ type: 'text' },
      beschreibung:   { type: 'richtext' },
      ort:            { type: 'string' },
      region:         { type: 'string' },
      hoehe:          { type: 'string' },
      dauer:          { type: 'string', desc: 'z.B. "1-2 Stunden"' },
      preis:          { type: 'string', desc: 'z.B. "12 € (Erwachsene)"' },
      oeffnungszeiten:{ type: 'string' },
      koordinaten:    { type: 'string' },
      webseite:       { type: 'url' },
      tags:           { type: 'array', items: 'string' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/sehenswuerdigkeiten/goldenes-dachl/aussen.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/sehenswuerdigkeiten/goldenes-dachl/hero.webp)' },
    },
    related: [],
  },

  magazin: {
    label: 'Magazin-Artikel',
    slugLabel: 'titel',
    fields: {
      titel:          { type: 'string', required: true },
      teaser:         { type: 'text' },
      datum:          { type: 'date' },
      autor:          { type: 'string' },
      kategorie:      { type: 'string' },
      tags:           { type: 'array', items: 'string' },
      inhalt:         { type: 'richtext', desc: 'HTML-Content des Artikels' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/magazin/artikel/teaser.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/magazin/artikel/hero.webp)' },
    },
    related: [],
  },

  erlebnisse: {
    label: 'Erlebnisse & Aktivitäten',
    slugLabel: 'name',
    fields: {
      name:           { type: 'string', required: true },
      slug:           { type: 'string', desc: 'URL-Slug (auto-generiert)' },
      emoji:          { type: 'string' },
      farbe:          { type: 'string' },
      kategorie:      { type: 'enum', values: ['wandern', 'ski', 'bike', 'wellness', 'familie', 'kulinarik', 'kultur', 'abenteuer'] },
      ort:            { type: 'string' },
      region:         { type: 'string' },
      beschreibung:   { type: 'richtext' },
      preis:          { type: 'number', desc: 'Preis in €' },
      dauer:          { type: 'string', desc: 'z.B. "2–3 Stunden"' },
      link:           { type: 'url', desc: 'Externer Link für Buchung/Info' },
      tags:           { type: 'array', items: 'string' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/erlebnisse/paragliding/action.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/erlebnisse/paragliding/hero.webp)' },
    },
    related: [],
  },

  events: {
    label: 'Events & Veranstaltungen',
    slugLabel: 'name',
    fields: {
      name:           { type: 'string' },
      titel:          { type: 'string', desc: 'Fallback wenn name fehlt' },
      emoji:          { type: 'string' },
      farbe:          { type: 'string' },
      datum:          { type: 'date' },
      datum_von:      { type: 'date', desc: 'Startdatum bei mehrtägig' },
      ort:            { type: 'string' },
      region:         { type: 'string' },
      kurzbeschreibung:{ type: 'text' },
      beschreibung:   { type: 'richtext' },
      preis:          { type: 'string' },
      kategorie:      { type: 'string' },
      uhrzeit:        { type: 'string' },
      link:           { type: 'url' },
      webseite:       { type: 'url' },
      tags:           { type: 'array', items: 'string' },
      status:         { type: 'enum', values: ['published', 'draft', 'archived'] },
      bilder:         { type: 'array', items: 'string', desc: 'Bild-URLs (z.B. /images/events/bergfest/gruppe.webp)' },
      hero_bild:      { type: 'string', desc: 'Hero-Hintergrundbild (z.B. /images/events/bergfest/hero.webp)' },
    },
    related: [],
  },
};

export const SINGLETONS = {
  home: {
    label: 'Homepage (JSON-basiert)',
    fields: ['hero_titel', 'hero_sub', 'hero_cta', 'stats'],
  },
  einstellungen: {
    label: 'Site-Einstellungen',
    fields: ['site_name', 'site_description', 'kontakt_email', 'kontakt_telefon', 'social'],
  },
  bezirke: {
    label: 'Bezirke Tirols (Singleton)',
    fields: ['innsbruck', 'innsbruck-land', 'imst', 'landeck', 'reutte', 'kufstein', 'kitzbuehel', 'schwaz', 'lienz'],
  },
  homepage: {
    label: 'Homepage (vollständig, alt)',
    fields: ['hero', 'stats', 'seelen', 'whyTirol', 'regionen', 'unterkuenfte', 'activities', 'events', 'magazin'],
  },
};
